# Generated by Django 5.2.4 on 2025-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='Telegram ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('group', models.CharField(max_length=25, verbose_name='Команда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
